### ISSUE TITLE
Details about running and training Models

### ISSUE THREAD

**Issue by amitsrivastava78** [swordcheng/FCSR-GAN#2]
Hi,
   Went though your paper and it is quite impressive, can you please provide the details about training and running model(pre-trained if possible). So that i can independently evaluate the paper

Regards
Amit

**Comment by swordcheng** [comment]
I will update the training details and pre-trained model in several days.

**Comment by swordcheng** [comment]
> Hi,
> Went though your paper and it is quite impressive, can you please provide the details about training and running model(pre-trained if possible). So that i can independently evaluate the paper
> 
> Regards
> Amit
